# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74c403330d16287250f158faf856977ab4a230a41893774813cfae2ff95f6fb43d46038b1844115cf54b4c870d01d932c503f29f45be57309700a651815b1489

test:
  secret_key_base: deef8637c2241655a9cb6b98b28c4351b02fb09b2925b5f0d2bc848ee5c00a12526209cf870230a2af99c298ac9098678e21c79917fa59e6b70253f0bba67b8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
